DROP DATABASE IF EXISTS Album;
CREATE DATABASE Album;
USE Album;

CREATE TABLE Disco(
Id_Disco INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
N_Disco	 VARCHAR(50),
Artista  VARCHAR(50),
Descrip	 VARCHAR(50),
Cantidad INT(4));

